### ISSUE TITLE
the icons of both next and previous month buttons are mirrored in RTL direction

### ISSUE THREAD

**Issue by sorousht** [smrsan76/imrc-datetime-picker#2]
The icons of next and previous month buttons flips in RTL direction which is confusing for users.

**To Reproduce**
1. Go to 'https://imrc-datetime-picker.js.org/'
2. Set the document direction to "rtl"

**Screenshots**
![imrc-datetime-picker](https://user-images.githubusercontent.com/3072018/50725315-2a1a6580-1111-11e9-9698-8e0e2a7b5cc6.png)

**Please complete the following information**
- OS: Windows 10...
- Browser: Firefox Version 64.0
- Webpack: v4.19
- Node.js: v10.14.2

**Comment by smrsan76** [comment]
Hi @sorousht 
Thanks for submitting issue.

I've just fixed this issue in v2.0.2.

If there was another issue, your next contributions are appreciated.
