### ISSUE TITLE
The day of week is not correct in FA language

### ISSUE THREAD

**Issue by sorousht** [smrsan76/imrc-datetime-picker#3]
**Describe the bug**
Saturday is the starting day of Persian weeks. But the starting day of the calandar in Solar Date mode is Sunday, although the day of week is Saturday in the header.
Please take a look at the provided screenshot and compare with the calendar in [time.ir](https://www.time.ir/).

**To Reproduce**
1. Visit the demo page
2. Check both "Solar Date" and "FA (language)" options

**Expected behavior**
It is expected to see "د" (wich represents Monday in FA) for 1397-11-1

**Screenshots**
![screenshot from 2019-01-21 17-01-59](https://user-images.githubusercontent.com/3072018/51477737-9c8c7600-1d9e-11e9-82dd-fad979f32451.png)

**Comment by smrsan76** [comment]
Hi @sorousht 
Thanks a lot for being careful about these small & very important bugs.
I was shocked because of this ridiculous bug !

I've just fixed this issue in v2.1.0.

If there was another issue, your next contributions are appreciated.
